# Generated by Django 3.1.3 on 2021-01-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistore', '0002_auto_20210117_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
    ]
