# Generated by Django 3.1.3 on 2021-01-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistore', '0005_auto_20210117_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
