# Generated by Django 3.1.3 on 2021-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210111_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Mobile', 'Mobile'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Appliances', 'Appliances'), ('Sports', 'Sports'), ('Books', 'Books'), ('Furniture', 'Furniture')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
