# Generated by Django 3.1.3 on 2021-01-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210111_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='dateordered',
        ),
    ]
